# Project Information
site_name: Subsidence System for Insight and Data Exploration
site_url: https://in-for-disaster-analytics.github.io/subside/
site_author: UT Austin DSO Team
site_description:  >-
  Website for the Subside Project

# Repository
repo_name: In-For-Disaster-Analytics/subside
repo_url: https://github.com/In-For-Disaster-Analytics/subside

# Configuration
theme:
  logo: assets/pt2050/pillar1.svg 
  # https://cdn.jsdelivr.net/gh/TACC/Core-CMS-Custom@813aa7c/ptdatax_assets/logo.png
  name: material
  custom_dir: overrides
  features:
    - content.code.annotate 
    - content.code.copy
    - content.code.select
    - header.autohide
    - navigation.expand
    # - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs    
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
    # - toc.integrate
  font:
    text: "'Benton Sans', 'Open Sans'" # "Benton Sans" available via tacc/core-styles.css
    code: Roboto
  favicon: https://cdn.jsdelivr.net/gh/TACC/Core-CMS-Custom@813aa7c/ptdatax_assets/favicon.ico

  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode        
  
    
extra_css:
  - stylesheets/tacc.css
  - stylesheets/extra.css
   
extra_javascript:
  # - javascripts/extra.js  
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true          

plugins:
  - awesome-pages:
      # filename: .index
      collapse_single_pages: true
      strict: false
      order: asc
      sort_type: natural
      # order_by: title
  # - mkdocs-pdf
  # - multirepo:
  #     # (optional) tells multirepo to cleanup the temporary directory after site is built.
  #     cleanup: true
  #     # if set the docs directory will not be removed when importing docs.
  #     # When using this with a nav section in an imported repo you must keep the
  #     # docs directory in the path (e.g., docs/path/to/file.md).
  #     keep_docs_dir: true
  - privacy:
      assets: false
      external_links_attr_map:
        target: _blank
  - search
